import { ReportCardTemplate } from './templateService';

export const MOCK_TEMPLATES: ReportCardTemplate[] = [
    {
        id: '1',
        name: 'Standard Report Card',
        description: 'A comprehensive, traditional report card template suitable for most schools.',
        version: '1.0',
        paperSize: 'A4',
        orientation: 'portrait',
        isActive: true,
        isDefault: true,
        isPublished: true,
        usageCount: 45,
        lastUsed: '2024-01-15T10:30:00Z',
        createdAt: '2024-01-01T00:00:00Z',
        creatorName: 'System',
        assignmentsCount: 8,
        elements: [
            // Header Section
            {
                id: 'header-bg',
                type: 'school_header',
                content: 'SPRINGFIELD HIGH SCHOOL\nExcellence in Education',
                x: 0,
                y: 0,
                width: 794,
                height: 120,
                fontSize: 28,
                fontFamily: 'Times New Roman',
                fontWeight: 'bold',
                textAlign: 'center',
                color: '#ffffff',
                backgroundColor: '#1e3a8a', // Dark Blue
                padding: 20,
                zIndex: 1,
                visible: true,
            },
            {
                id: 'sub-header',
                type: 'text',
                content: 'ACADEMIC REPORT CARD\n2024 - 2025',
                x: 0,
                y: 130,
                width: 794,
                height: 60,
                fontSize: 18,
                fontFamily: 'Arial',
                fontWeight: 'bold',
                textAlign: 'center',
                color: '#1e3a8a',
                zIndex: 1,
                visible: true,
            },
            // Student Info Section (Left)
            {
                id: 'student-info-left',
                type: 'student_info',
                content: 'Student Name: [Student Name]\nClass: [Class Name]\nRoll No: [Roll Number]',
                x: 40,
                y: 200,
                width: 350,
                height: 100,
                fontSize: 14,
                fontFamily: 'Arial',
                textAlign: 'left',
                color: '#374151',
                zIndex: 1,
                visible: true,
            },
            // Student Info Section (Right)
            {
                id: 'student-info-right',
                type: 'text',
                content: 'Date of Birth: [DOB]\nParent/Guardian: [Parent Name]\nAttendance: [Attendance %]',
                x: 404,
                y: 200,
                width: 350,
                height: 100,
                fontSize: 14,
                fontFamily: 'Arial',
                textAlign: 'right',
                color: '#374151',
                zIndex: 1,
                visible: true,
            },
            // Divider
            {
                id: 'divider-1',
                type: 'text',
                content: '',
                x: 40,
                y: 290,
                width: 714,
                height: 2,
                backgroundColor: '#e5e7eb',
                zIndex: 1,
                visible: true,
            },
            // Grades Table
            {
                id: 'grades-table',
                type: 'grade_table',
                content: 'Academic Performance',
                x: 40,
                y: 320,
                width: 714,
                height: 400,
                zIndex: 1,
                visible: true,
                properties: {
                    showRemarks: true,
                    striped: true,
                    compact: false,
                    headerBackgroundColor: '#1e3a8a',
                    headerTextColor: '#ffffff',
                }
            },
            // Attendance Summary
            {
                id: 'attendance-table',
                type: 'attendance_table',
                content: 'Attendance Summary',
                x: 40,
                y: 750,
                width: 714,
                height: 150,
                zIndex: 1,
                visible: true,
                properties: {
                    striped: true,
                    headerBackgroundColor: '#f3f4f6',
                    headerTextColor: '#374151',
                }
            },
            // Signatures
            {
                id: 'sig-teacher',
                type: 'text',
                content: '____________________\nClass Teacher',
                x: 40,
                y: 950,
                width: 200,
                height: 60,
                fontSize: 14,
                textAlign: 'center',
                zIndex: 1,
                visible: true,
            },
            {
                id: 'sig-principal',
                type: 'text',
                content: '____________________\nPrincipal',
                x: 554,
                y: 950,
                width: 200,
                height: 60,
                fontSize: 14,
                textAlign: 'center',
                zIndex: 1,
                visible: true,
            },
            // Footer
            {
                id: 'footer',
                type: 'text',
                content: 'Generated by School Management System',
                x: 0,
                y: 1080,
                width: 794,
                height: 30,
                fontSize: 10,
                textAlign: 'center',
                color: '#9ca3af',
                zIndex: 1,
                visible: true,
            }
        ]
    },
    {
        id: '2',
        name: 'Minimal Report Card',
        description: 'A clean, minimalist design focusing on typography and whitespace.',
        version: '1.2',
        paperSize: 'A4',
        orientation: 'portrait',
        isActive: true,
        isDefault: false,
        isPublished: true,
        usageCount: 23,
        lastUsed: '2024-01-14T14:20:00Z',
        createdAt: '2024-01-05T00:00:00Z',
        creatorName: 'System',
        assignmentsCount: 3,
        elements: [
            // Minimal Header
            {
                id: 'min-header-school',
                type: 'school_header',
                content: 'Springfield High.',
                x: 50,
                y: 50,
                width: 400,
                height: 60,
                fontSize: 32,
                fontFamily: 'Helvetica',
                fontWeight: 'bold',
                textAlign: 'left',
                color: '#000000',
                zIndex: 1,
                visible: true,
            },
            {
                id: 'min-header-title',
                type: 'text',
                content: 'REPORT CARD',
                x: 544,
                y: 60,
                width: 200,
                height: 40,
                fontSize: 14,
                fontFamily: 'Helvetica',
                fontWeight: 'bold',
                textAlign: 'right',
                color: '#9ca3af',
                zIndex: 1,
                visible: true,
            },
            // Thick Divider
            {
                id: 'min-divider-1',
                type: 'text',
                content: '',
                x: 50,
                y: 110,
                width: 694,
                height: 4,
                backgroundColor: '#000000',
                zIndex: 1,
                visible: true,
            },
            // Student Details (Grid Layout)
            {
                id: 'min-student-name',
                type: 'text',
                content: 'STUDENT\n[Student Name]',
                x: 50,
                y: 140,
                width: 200,
                height: 60,
                fontSize: 12,
                fontFamily: 'Helvetica',
                color: '#6b7280', // Label color
                zIndex: 1,
                visible: true,
            },
            {
                id: 'min-student-class',
                type: 'text',
                content: 'CLASS\n[Class Name]',
                x: 250,
                y: 140,
                width: 150,
                height: 60,
                fontSize: 12,
                fontFamily: 'Helvetica',
                color: '#6b7280',
                zIndex: 1,
                visible: true,
            },
            {
                id: 'min-student-roll',
                type: 'text',
                content: 'ROLL NO\n[Roll Number]',
                x: 400,
                y: 140,
                width: 150,
                height: 60,
                fontSize: 12,
                fontFamily: 'Helvetica',
                color: '#6b7280',
                zIndex: 1,
                visible: true,
            },
            {
                id: 'min-student-year',
                type: 'text',
                content: 'ACADEMIC YEAR\n2024-2025',
                x: 550,
                y: 140,
                width: 194,
                height: 60,
                fontSize: 12,
                fontFamily: 'Helvetica',
                textAlign: 'right',
                color: '#6b7280',
                zIndex: 1,
                visible: true,
            },
            // Grades
            {
                id: 'min-grades',
                type: 'grade_table',
                content: 'Performance',
                x: 50,
                y: 240,
                width: 694,
                height: 500,
                zIndex: 1,
                visible: true,
                properties: {
                    showRemarks: true,
                    striped: false,
                    compact: true,
                    headerBackgroundColor: '#ffffff',
                    headerTextColor: '#000000',
                }
            },
            // Bottom Section
            {
                id: 'min-divider-2',
                type: 'text',
                content: '',
                x: 50,
                y: 800,
                width: 694,
                height: 1,
                backgroundColor: '#e5e7eb',
                zIndex: 1,
                visible: true,
            },
            {
                id: 'min-remarks',
                type: 'text',
                content: 'TEACHER REMARKS\n\nExcellent performance this semester. Keep up the good work.',
                x: 50,
                y: 830,
                width: 694,
                height: 100,
                fontSize: 12,
                fontFamily: 'Helvetica',
                textAlign: 'left',
                color: '#374151',
                zIndex: 1,
                visible: true,
            },
            {
                id: 'min-sig',
                type: 'text',
                content: 'AUTHORIZED SIGNATURE',
                x: 544,
                y: 980,
                width: 200,
                height: 40,
                fontSize: 10,
                fontFamily: 'Helvetica',
                textAlign: 'right',
                color: '#9ca3af',
                zIndex: 1,
                visible: true,
            },
        ]
    },
    {
        id: '3',
        name: 'Landscape Report Card',
        description: 'A modern landscape layout with a sidebar for student details.',
        version: '2.0',
        paperSize: 'A4',
        orientation: 'landscape',
        isActive: true,
        isDefault: false,
        isPublished: false,
        usageCount: 12,
        lastUsed: '2024-01-10T09:15:00Z',
        createdAt: '2024-01-10T00:00:00Z',
        creatorName: 'System',
        assignmentsCount: 1,
        elements: [
            // Sidebar Background (Simulated with Text element)
            {
                id: 'land-sidebar-bg',
                type: 'text',
                content: '',
                x: 0,
                y: 0,
                width: 300,
                height: 794,
                backgroundColor: '#1f2937', // Dark Gray
                zIndex: 0,
                visible: true,
            },
            // Sidebar Content
            {
                id: 'land-school-name',
                type: 'school_header',
                content: 'SPRINGFIELD\nHIGH SCHOOL',
                x: 30,
                y: 40,
                width: 240,
                height: 100,
                fontSize: 24,
                fontFamily: 'Arial',
                fontWeight: 'bold',
                textAlign: 'left',
                color: '#ffffff',
                zIndex: 1,
                visible: true,
            },
            {
                id: 'land-student-photo',
                type: 'text', // Placeholder for photo
                content: '[PHOTO]',
                x: 30,
                y: 160,
                width: 100,
                height: 100,
                backgroundColor: '#374151',
                color: '#9ca3af',
                textAlign: 'center',
                fontSize: 12,
                zIndex: 1,
                visible: true,
                borderRadius: 8,
            },
            {
                id: 'land-student-info',
                type: 'student_info',
                content: 'NAME\n[Student Name]\n\nCLASS\n[Class Name]\n\nROLL NO\n[Roll Number]\n\nDOB\n[DOB]',
                x: 30,
                y: 280,
                width: 240,
                height: 300,
                fontSize: 14,
                fontFamily: 'Arial',
                color: '#e5e7eb',
                textAlign: 'left',
                zIndex: 1,
                visible: true,
            },
            // Main Content Area (Right)
            {
                id: 'land-title',
                type: 'text',
                content: 'PROGRESS REPORT',
                x: 340,
                y: 40,
                width: 743, // 1123 - 340 - 40
                height: 50,
                fontSize: 24,
                fontFamily: 'Arial',
                fontWeight: 'bold',
                textAlign: 'right',
                color: '#1f2937',
                zIndex: 1,
                visible: true,
            },
            {
                id: 'land-term',
                type: 'text',
                content: 'TERM 1 / 2024-2025',
                x: 340,
                y: 80,
                width: 743,
                height: 30,
                fontSize: 14,
                fontFamily: 'Arial',
                textAlign: 'right',
                color: '#6b7280',
                zIndex: 1,
                visible: true,
            },
            // Grades Table
            {
                id: 'land-grades',
                type: 'grade_table',
                content: 'Subject Performance',
                x: 340,
                y: 140,
                width: 743,
                height: 400,
                zIndex: 1,
                visible: true,
                properties: {
                    showRemarks: true,
                    striped: true,
                    headerBackgroundColor: '#f3f4f6',
                    headerTextColor: '#1f2937',
                }
            },
            // Attendance & Remarks (Bottom Right)
            {
                id: 'land-attendance',
                type: 'attendance_table',
                content: 'Attendance',
                x: 340,
                y: 570,
                width: 350,
                height: 150,
                zIndex: 1,
                visible: true,
                properties: {
                    compact: true,
                }
            },
            {
                id: 'land-remarks-box',
                type: 'text',
                content: 'REMARKS\n\n[Teacher Remarks]',
                x: 733,
                y: 570,
                width: 350,
                height: 150,
                backgroundColor: '#f9fafb',
                borderWidth: 1,
                borderColor: '#e5e7eb',
                padding: 15,
                fontSize: 12,
                zIndex: 1,
                visible: true,
            },
        ]
    }
];
