"""Add user_id to Student and create StudentClassHistory model

Revision ID: 11fd581012af
Revises: 9f6604f067d1
Create Date: 2025-10-11 17:56:21.543201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fd581012af'
down_revision = '9f6604f067d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_class_history',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('academic_session', sa.String(length=20), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PROMOTED', 'REPEATED', 'TRANSFERRED', name='classhistorystatus'), nullable=False),
    sa.Column('promoted_to_class_id', sa.String(length=36), nullable=True),
    sa.Column('promotion_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['promoted_to_class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('students', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'students', ['user_id'])
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'user_id')
    op.drop_table('student_class_history')
    # ### end Alembic commands ###
