"""Add multi-tenant blockchain fields

Revision ID: 1a5493c3a452
Revises: b2e0f48052e6
Create Date: 2025-12-17 16:47:11.914758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5493c3a452'
down_revision = 'b2e0f48052e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('blockchain_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('schools', sa.Column('wallet_address', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('encrypted_signing_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'encrypted_signing_key')
    op.drop_column('schools', 'wallet_address')
    op.drop_column('schools', 'blockchain_enabled')
    # ### end Alembic commands ###
