"""add_report_card_template_tables

Revision ID: 5ebbf8b973da
Revises: 7c94917d7c66
Create Date: 2025-09-28 02:15:59.718111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebbf8b973da'
down_revision = '7c94917d7c66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
