"""Add teacher materials management tables

Revision ID: 6390eac7eb62
Revises: 11fd581012af
Create Date: 2025-10-11 21:49:33.924821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6390eac7eb62'
down_revision = '11fd581012af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_folders',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_folder_id', sa.String(length=36), nullable=True),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['material_folders.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_folders_school_id'), 'material_folders', ['school_id'], unique=False)
    op.create_index(op.f('ix_material_folders_teacher_id'), 'material_folders', ['teacher_id'], unique=False)
    op.create_table('teacher_materials',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('material_type', sa.Enum('DOCUMENT', 'PDF', 'PRESENTATION', 'SPREADSHEET', 'IMAGE', 'VIDEO', 'AUDIO', 'ARCHIVE', 'OTHER', name='materialtype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('grade_level', sa.String(length=50), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_publish_at', sa.DateTime(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_material_id', sa.String(length=36), nullable=True),
    sa.Column('is_current_version', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_material_id'], ['teacher_materials.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_materials_school_id'), 'teacher_materials', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_materials_title'), 'teacher_materials', ['title'], unique=False)
    op.create_index(op.f('ix_teacher_materials_uploaded_by'), 'teacher_materials', ['uploaded_by'], unique=False)
    op.create_table('material_access_logs',
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('access_type', sa.Enum('VIEW', 'DOWNLOAD', 'PREVIEW', name='accesstype'), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['teacher_materials.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_access_logs_accessed_at'), 'material_access_logs', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_material_access_logs_material_id'), 'material_access_logs', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_access_logs_school_id'), 'material_access_logs', ['school_id'], unique=False)
    op.create_index(op.f('ix_material_access_logs_user_id'), 'material_access_logs', ['user_id'], unique=False)
    op.create_table('material_folder_items',
    sa.Column('folder_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['material_folders.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['teacher_materials.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_folder_items_folder_id'), 'material_folder_items', ['folder_id'], unique=False)
    op.create_index(op.f('ix_material_folder_items_material_id'), 'material_folder_items', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_folder_items_school_id'), 'material_folder_items', ['school_id'], unique=False)
    op.create_table('material_shares',
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('share_type', sa.Enum('CLASS', 'STUDENT_GROUP', 'INDIVIDUAL_STUDENT', 'TEACHER', 'ALL_STUDENTS', name='sharetype'), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('can_download', sa.Boolean(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('shared_by', sa.String(length=36), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['teacher_materials.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_shares_material_id'), 'material_shares', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_shares_school_id'), 'material_shares', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_shares_school_id'), table_name='material_shares')
    op.drop_index(op.f('ix_material_shares_material_id'), table_name='material_shares')
    op.drop_table('material_shares')
    op.drop_index(op.f('ix_material_folder_items_school_id'), table_name='material_folder_items')
    op.drop_index(op.f('ix_material_folder_items_material_id'), table_name='material_folder_items')
    op.drop_index(op.f('ix_material_folder_items_folder_id'), table_name='material_folder_items')
    op.drop_table('material_folder_items')
    op.drop_index(op.f('ix_material_access_logs_user_id'), table_name='material_access_logs')
    op.drop_index(op.f('ix_material_access_logs_school_id'), table_name='material_access_logs')
    op.drop_index(op.f('ix_material_access_logs_material_id'), table_name='material_access_logs')
    op.drop_index(op.f('ix_material_access_logs_accessed_at'), table_name='material_access_logs')
    op.drop_table('material_access_logs')
    op.drop_index(op.f('ix_teacher_materials_uploaded_by'), table_name='teacher_materials')
    op.drop_index(op.f('ix_teacher_materials_title'), table_name='teacher_materials')
    op.drop_index(op.f('ix_teacher_materials_school_id'), table_name='teacher_materials')
    op.drop_table('teacher_materials')
    op.drop_index(op.f('ix_material_folders_teacher_id'), table_name='material_folders')
    op.drop_index(op.f('ix_material_folders_school_id'), table_name='material_folders')
    op.drop_table('material_folders')
    # ### end Alembic commands ###
