"""add_performance_indexes

Revision ID: 787b442df8cd
Revises: e112c31ccfb5
Create Date: 2026-01-04 11:37:25.091317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787b442df8cd'
down_revision = 'e112c31ccfb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_attendance_school_date', 'attendances', ['school_id', 'date'], unique=False)
    op.create_index('idx_attendance_student_term', 'attendances', ['student_id', 'term_id'], unique=False)
    op.create_index(op.f('ix_students_current_class_id'), 'students', ['current_class_id'], unique=False)
    op.create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    op.create_index(op.f('ix_students_status'), 'students', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_status'), table_name='students')
    op.drop_index(op.f('ix_students_school_id'), table_name='students')
    op.drop_index(op.f('ix_students_current_class_id'), table_name='students')
    op.drop_index('idx_attendance_student_term', table_name='attendances')
    op.drop_index('idx_attendance_school_date', table_name='attendances')
    # ### end Alembic commands ###
