"""Add children backref to MaterialFolder

Revision ID: 80b21cfb5199
Revises: 6390eac7eb62
Create Date: 2025-10-11 23:30:27.962793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b21cfb5199'
down_revision = '6390eac7eb62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
