"""Add school_owner_id to report card templates

Revision ID: 9f6604f067d1
Revises: 5ebbf8b973da
Create Date: 2025-09-28 17:20:35.581245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6604f067d1'
down_revision = '5ebbf8b973da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_card_templates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('paper_size', sa.Enum('A4', 'A3', 'LETTER', 'LEGAL', 'TABLOID', name='papersize'), nullable=False),
    sa.Column('orientation', sa.Enum('PORTRAIT', 'LANDSCAPE', name='orientation'), nullable=False),
    sa.Column('page_margin_top', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('page_margin_bottom', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('page_margin_left', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('page_margin_right', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('background_color', sa.String(length=7), nullable=False),
    sa.Column('background_image_url', sa.String(length=500), nullable=True),
    sa.Column('default_font_family', sa.String(length=50), nullable=False),
    sa.Column('default_font_size', sa.Integer(), nullable=False),
    sa.Column('default_text_color', sa.String(length=7), nullable=False),
    sa.Column('default_line_height', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.String(length=50), nullable=True),
    sa.Column('school_owner_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['school_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_card_template_assignments',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.String(length=50), nullable=True),
    sa.Column('effective_until', sa.String(length=50), nullable=True),
    sa.Column('auto_generate', sa.Boolean(), nullable=False),
    sa.Column('require_approval', sa.Boolean(), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('school_owner_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['school_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_card_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_card_template_fields',
    sa.Column('field_id', sa.String(length=50), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'NUMBER', 'DATE', 'IMAGE', 'TABLE', 'SIGNATURE', 'BARCODE', 'STUDENT_INFO', 'GRADE_TABLE', 'ATTENDANCE', 'COMMENTS', 'SCHOOL_HEADER', 'PERFORMANCE_SUMMARY', name='fieldtype'), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('x_position', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('y_position', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('width', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('height', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('font_family', sa.String(length=50), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('font_weight', sa.Enum('NORMAL', 'BOLD', 'LIGHTER', 'BOLDER', name='fontweight'), nullable=False),
    sa.Column('font_style', sa.Enum('NORMAL', 'ITALIC', 'OBLIQUE', name='fontstyle'), nullable=False),
    sa.Column('text_color', sa.String(length=7), nullable=True),
    sa.Column('background_color', sa.String(length=7), nullable=True),
    sa.Column('border_color', sa.String(length=7), nullable=True),
    sa.Column('border_width', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('border_style', sa.String(length=20), nullable=False),
    sa.Column('text_align', sa.Enum('LEFT', 'CENTER', 'RIGHT', 'JUSTIFY', name='alignment'), nullable=False),
    sa.Column('line_height', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('placeholder_text', sa.String(length=200), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('school_owner_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_card_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_card_template_fields_school_id'), 'report_card_template_fields', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_card_template_fields_school_id'), table_name='report_card_template_fields')
    op.drop_table('report_card_template_fields')
    op.drop_table('report_card_template_assignments')
    op.drop_table('report_card_templates')
    # ### end Alembic commands ###
