"""add_student_goals_alerts_curriculum_tables

Revision ID: b2afa869843a
Revises: f0040b89e855
Create Date: 2025-12-04 20:53:27.873824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2afa869843a'
down_revision = 'f0040b89e855'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alert_type', sa.Enum('ATTENDANCE', 'GRADE', 'FEE', 'BEHAVIOR', 'ENROLLMENT', 'CUSTOM', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.Enum('LESS_THAN', 'LESS_THAN_OR_EQUAL', 'GREATER_THAN', 'GREATER_THAN_OR_EQUAL', 'EQUAL', 'NOT_EQUAL', name='alertconditionoperator'), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=True),
    sa.Column('notify_roles', sa.JSON(), nullable=True),
    sa.Column('notify_users', sa.JSON(), nullable=True),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('frequency', sa.Enum('REALTIME', 'HOURLY', 'DAILY', 'WEEKLY', name='alertfrequency'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('next_evaluation_at', sa.DateTime(), nullable=True),
    sa.Column('additional_config', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_school_id'), 'alert_rules', ['school_id'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.Enum('REALTIME', 'HOURLY', 'DAILY', 'WEEKLY', name='alertfrequency'), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=True),
    sa.Column('time_of_day', sa.String(length=5), nullable=True),
    sa.Column('recipient_roles', sa.JSON(), nullable=True),
    sa.Column('recipient_users', sa.JSON(), nullable=True),
    sa.Column('delivery_channels', sa.JSON(), nullable=True),
    sa.Column('report_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_reports_school_id'), 'scheduled_reports', ['school_id'], unique=False)
    op.create_table('alert_notifications',
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=True),
    sa.Column('context_id', sa.String(length=36), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_notifications_rule_id'), 'alert_notifications', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_notifications_school_id'), 'alert_notifications', ['school_id'], unique=False)
    op.create_table('curriculum_units',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('coverage_status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='coveragestatus'), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('actual_hours', sa.Integer(), nullable=True),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_units_class_id'), 'curriculum_units', ['class_id'], unique=False)
    op.create_index(op.f('ix_curriculum_units_school_id'), 'curriculum_units', ['school_id'], unique=False)
    op.create_index(op.f('ix_curriculum_units_subject_id'), 'curriculum_units', ['subject_id'], unique=False)
    op.create_index(op.f('ix_curriculum_units_term_id'), 'curriculum_units', ['term_id'], unique=False)
    op.create_table('lesson_plan_items',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('curriculum_unit_id', sa.String(length=36), nullable=True),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('delivered_date', sa.Date(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('activities', sa.JSON(), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.Column('assessment_methods', sa.JSON(), nullable=True),
    sa.Column('ai_generated_content', sa.Text(), nullable=True),
    sa.Column('reflection_notes', sa.Text(), nullable=True),
    sa.Column('student_engagement_rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['curriculum_unit_id'], ['curriculum_units.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plan_items_class_id'), 'lesson_plan_items', ['class_id'], unique=False)
    op.create_index(op.f('ix_lesson_plan_items_curriculum_unit_id'), 'lesson_plan_items', ['curriculum_unit_id'], unique=False)
    op.create_index(op.f('ix_lesson_plan_items_school_id'), 'lesson_plan_items', ['school_id'], unique=False)
    op.create_index(op.f('ix_lesson_plan_items_subject_id'), 'lesson_plan_items', ['subject_id'], unique=False)
    op.create_index(op.f('ix_lesson_plan_items_teacher_id'), 'lesson_plan_items', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_lesson_plan_items_term_id'), 'lesson_plan_items', ['term_id'], unique=False)
    op.create_table('student_goals',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('ACADEMIC', 'ATTENDANCE', 'BEHAVIOR', 'EXTRACURRICULAR', 'PERSONAL', name='goalcategory'), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('target_unit', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='goalstatus'), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('term_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_goals_school_id'), 'student_goals', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_goals_student_id'), 'student_goals', ['student_id'], unique=False)
    op.create_table('goal_milestones',
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['student_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_milestones_goal_id'), 'goal_milestones', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_milestones_school_id'), 'goal_milestones', ['school_id'], unique=False)
    op.drop_index('ix_assessment_components_school_id', table_name='assessment_components')
    op.drop_index('ix_assessment_components_template_id', table_name='assessment_components')
    op.drop_constraint('assessment_components_template_id_fkey', 'assessment_components', type_='foreignkey')
    op.create_foreign_key(None, 'assessment_components', 'grade_templates', ['template_id'], ['id'])
    op.alter_column('component_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('component_mappings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('component_mappings', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_component_mappings_school_id'), 'component_mappings', ['school_id'], unique=False)
    op.drop_constraint('component_mappings_teacher_id_fkey', 'component_mappings', type_='foreignkey')
    op.drop_constraint('component_mappings_component_id_fkey', 'component_mappings', type_='foreignkey')
    op.drop_constraint('component_mappings_subject_id_fkey', 'component_mappings', type_='foreignkey')
    op.drop_constraint('component_mappings_school_id_fkey', 'component_mappings', type_='foreignkey')
    op.drop_constraint('component_mappings_term_id_fkey', 'component_mappings', type_='foreignkey')
    op.create_foreign_key(None, 'component_mappings', 'terms', ['term_id'], ['id'])
    op.create_foreign_key(None, 'component_mappings', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'component_mappings', 'assessment_components', ['component_id'], ['id'])
    op.create_foreign_key(None, 'component_mappings', 'subjects', ['subject_id'], ['id'])
    op.drop_index('ix_grade_scales_school_id', table_name='grade_scales')
    op.drop_index('ix_grade_scales_template_id', table_name='grade_scales')
    op.drop_constraint('grade_scales_template_id_fkey', 'grade_scales', type_='foreignkey')
    op.create_foreign_key(None, 'grade_scales', 'grade_templates', ['template_id'], ['id'])
    op.drop_index('ix_grade_templates_is_default', table_name='grade_templates')
    op.drop_index('ix_grade_templates_school_id', table_name='grade_templates')
    op.alter_column('grades', 'component_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint('material_access_logs_school_id_fkey', 'material_access_logs', type_='foreignkey')
    op.drop_constraint('material_folder_items_school_id_fkey', 'material_folder_items', type_='foreignkey')
    op.drop_constraint('material_folders_school_id_fkey', 'material_folders', type_='foreignkey')
    op.drop_constraint('material_shares_school_id_fkey', 'material_shares', type_='foreignkey')
    op.drop_index('ix_remark_templates_school_id', table_name='remark_templates')
    op.drop_index('ix_remark_templates_template_id', table_name='remark_templates')
    op.drop_constraint('remark_templates_template_id_fkey', 'remark_templates', type_='foreignkey')
    op.create_foreign_key(None, 'remark_templates', 'grade_templates', ['template_id'], ['id'])
    op.add_column('teacher_materials', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.add_column('teacher_materials', sa.Column('term_id', sa.String(length=36), nullable=True))
    # Create the enum type first before using it
    difficultylevel_enum = postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel', create_type=False)
    difficultylevel_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('teacher_materials', sa.Column('difficulty_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=True))
    op.add_column('teacher_materials', sa.Column('exam_type', sa.String(length=100), nullable=True))
    op.add_column('teacher_materials', sa.Column('keywords', sa.JSON(), nullable=True))
    op.add_column('teacher_materials', sa.Column('content_summary', sa.Text(), nullable=True))
    op.create_index(op.f('ix_teacher_materials_class_id'), 'teacher_materials', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_materials_subject_id'), 'teacher_materials', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_materials_term_id'), 'teacher_materials', ['term_id'], unique=False)
    op.drop_constraint('teacher_materials_school_id_fkey', 'teacher_materials', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_materials', 'classes', ['class_id'], ['id'])
    op.create_foreign_key(None, 'teacher_materials', 'terms', ['term_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_materials', type_='foreignkey')
    op.drop_constraint(None, 'teacher_materials', type_='foreignkey')
    op.create_foreign_key('teacher_materials_school_id_fkey', 'teacher_materials', 'schools', ['school_id'], ['id'])
    op.drop_index(op.f('ix_teacher_materials_term_id'), table_name='teacher_materials')
    op.drop_index(op.f('ix_teacher_materials_subject_id'), table_name='teacher_materials')
    op.drop_index(op.f('ix_teacher_materials_class_id'), table_name='teacher_materials')
    op.drop_column('teacher_materials', 'content_summary')
    op.drop_column('teacher_materials', 'keywords')
    op.drop_column('teacher_materials', 'exam_type')
    op.drop_column('teacher_materials', 'difficulty_level')
    op.drop_column('teacher_materials', 'term_id')
    op.drop_column('teacher_materials', 'class_id')
    op.drop_constraint(None, 'remark_templates', type_='foreignkey')
    op.create_foreign_key('remark_templates_template_id_fkey', 'remark_templates', 'grade_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_remark_templates_template_id', 'remark_templates', ['template_id'], unique=False)
    op.create_index('ix_remark_templates_school_id', 'remark_templates', ['school_id'], unique=False)
    op.create_foreign_key('material_shares_school_id_fkey', 'material_shares', 'schools', ['school_id'], ['id'])
    op.create_foreign_key('material_folders_school_id_fkey', 'material_folders', 'schools', ['school_id'], ['id'])
    op.create_foreign_key('material_folder_items_school_id_fkey', 'material_folder_items', 'schools', ['school_id'], ['id'])
    op.create_foreign_key('material_access_logs_school_id_fkey', 'material_access_logs', 'schools', ['school_id'], ['id'])
    op.alter_column('grades', 'component_scores',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_grade_templates_school_id', 'grade_templates', ['school_id'], unique=False)
    op.create_index('ix_grade_templates_is_default', 'grade_templates', ['is_default'], unique=False)
    op.drop_constraint(None, 'grade_scales', type_='foreignkey')
    op.create_foreign_key('grade_scales_template_id_fkey', 'grade_scales', 'grade_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_grade_scales_template_id', 'grade_scales', ['template_id'], unique=False)
    op.create_index('ix_grade_scales_school_id', 'grade_scales', ['school_id'], unique=False)
    op.drop_constraint(None, 'component_mappings', type_='foreignkey')
    op.drop_constraint(None, 'component_mappings', type_='foreignkey')
    op.drop_constraint(None, 'component_mappings', type_='foreignkey')
    op.drop_constraint(None, 'component_mappings', type_='foreignkey')
    op.create_foreign_key('component_mappings_term_id_fkey', 'component_mappings', 'terms', ['term_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('component_mappings_school_id_fkey', 'component_mappings', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('component_mappings_subject_id_fkey', 'component_mappings', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('component_mappings_component_id_fkey', 'component_mappings', 'assessment_components', ['component_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('component_mappings_teacher_id_fkey', 'component_mappings', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_component_mappings_school_id'), table_name='component_mappings')
    op.alter_column('component_mappings', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('component_mappings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('component_mappings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'assessment_components', type_='foreignkey')
    op.create_foreign_key('assessment_components_template_id_fkey', 'assessment_components', 'grade_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_assessment_components_template_id', 'assessment_components', ['template_id'], unique=False)
    op.create_index('ix_assessment_components_school_id', 'assessment_components', ['school_id'], unique=False)
    op.drop_index(op.f('ix_goal_milestones_school_id'), table_name='goal_milestones')
    op.drop_index(op.f('ix_goal_milestones_goal_id'), table_name='goal_milestones')
    op.drop_table('goal_milestones')
    op.drop_index(op.f('ix_student_goals_student_id'), table_name='student_goals')
    op.drop_index(op.f('ix_student_goals_school_id'), table_name='student_goals')
    op.drop_table('student_goals')
    op.drop_index(op.f('ix_lesson_plan_items_term_id'), table_name='lesson_plan_items')
    op.drop_index(op.f('ix_lesson_plan_items_teacher_id'), table_name='lesson_plan_items')
    op.drop_index(op.f('ix_lesson_plan_items_subject_id'), table_name='lesson_plan_items')
    op.drop_index(op.f('ix_lesson_plan_items_school_id'), table_name='lesson_plan_items')
    op.drop_index(op.f('ix_lesson_plan_items_curriculum_unit_id'), table_name='lesson_plan_items')
    op.drop_index(op.f('ix_lesson_plan_items_class_id'), table_name='lesson_plan_items')
    op.drop_table('lesson_plan_items')
    op.drop_index(op.f('ix_curriculum_units_term_id'), table_name='curriculum_units')
    op.drop_index(op.f('ix_curriculum_units_subject_id'), table_name='curriculum_units')
    op.drop_index(op.f('ix_curriculum_units_school_id'), table_name='curriculum_units')
    op.drop_index(op.f('ix_curriculum_units_class_id'), table_name='curriculum_units')
    op.drop_table('curriculum_units')
    op.drop_index(op.f('ix_alert_notifications_school_id'), table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_rule_id'), table_name='alert_notifications')
    op.drop_table('alert_notifications')
    op.drop_index(op.f('ix_scheduled_reports_school_id'), table_name='scheduled_reports')
    op.drop_table('scheduled_reports')
    op.drop_index(op.f('ix_alert_rules_school_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
