"""Add transfer certificates

Revision ID: b2e0f48052e6
Revises: 2025121101
Create Date: 2025-12-17 16:14:00.367695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e0f48052e6'
down_revision = '2025121101'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_requests',
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=True),
    sa.Column('submitted_by', sa.String(length=36), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='promotionrequeststatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_requests_class_id'), 'promotion_requests', ['class_id'], unique=False)
    op.create_index(op.f('ix_promotion_requests_school_id'), 'promotion_requests', ['school_id'], unique=False)
    op.create_index(op.f('ix_promotion_requests_session_id'), 'promotion_requests', ['session_id'], unique=False)
    op.create_index(op.f('ix_promotion_requests_status'), 'promotion_requests', ['status'], unique=False)
    op.create_table('transfer_certificates',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=64), nullable=True),
    sa.Column('asset_name', sa.String(length=64), nullable=True),
    sa.Column('transaction_hash', sa.String(length=64), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MINTED', 'FAILED', name='certificatestatus'), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_certificates_school_id'), 'transfer_certificates', ['school_id'], unique=False)
    op.drop_index('ix_academic_sessions_is_current', table_name='academic_sessions')
    op.drop_index('ix_academic_sessions_name', table_name='academic_sessions')
    op.drop_index('ix_academic_sessions_school_id', table_name='academic_sessions')
    op.drop_constraint('uq_teacher_permission', 'teacher_permissions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_teacher_permission', 'teacher_permissions', ['school_id', 'teacher_id', 'permission_type'])
    op.create_index('ix_academic_sessions_school_id', 'academic_sessions', ['school_id'], unique=False)
    op.create_index('ix_academic_sessions_name', 'academic_sessions', ['name'], unique=False)
    op.create_index('ix_academic_sessions_is_current', 'academic_sessions', ['is_current'], unique=False)
    op.drop_index(op.f('ix_transfer_certificates_school_id'), table_name='transfer_certificates')
    op.drop_table('transfer_certificates')
    op.drop_index(op.f('ix_promotion_requests_status'), table_name='promotion_requests')
    op.drop_index(op.f('ix_promotion_requests_session_id'), table_name='promotion_requests')
    op.drop_index(op.f('ix_promotion_requests_school_id'), table_name='promotion_requests')
    op.drop_index(op.f('ix_promotion_requests_class_id'), table_name='promotion_requests')
    op.drop_table('promotion_requests')
    # ### end Alembic commands ###
