"""Add subject_id to attendance table

Revision ID: b729811a71f2
Revises: a8167fa0aaf7
Create Date: 2025-11-27 22:44:18.650611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b729811a71f2'
down_revision = 'a8167fa0aaf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('subject_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'attendances', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_column('attendances', 'subject_id')
    # ### end Alembic commands ###
