"""Add VerifiableCredential model

Revision ID: e112c31ccfb5
Revises: 1a5493c3a452
Create Date: 2025-12-17 17:00:11.826881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e112c31ccfb5'
down_revision = '1a5493c3a452'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifiable_credentials',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('credential_type', sa.Enum('TRANSFER', 'GRADE', 'ATTENDANCE', 'ACHIEVEMENT', name='credentialtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_id', sa.String(length=64), nullable=True),
    sa.Column('asset_name', sa.String(length=64), nullable=True),
    sa.Column('transaction_hash', sa.String(length=64), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'MINTED', 'FAILED', 'REVOKED', name='credentialstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifiable_credentials_school_id'), 'verifiable_credentials', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifiable_credentials_school_id'), table_name='verifiable_credentials')
    op.drop_table('verifiable_credentials')
    # ### end Alembic commands ###
